# version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpg_be_server
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}

    restart: always
    networks:
      - cpg-network

volumes:
  mongodb_data:

networks:
  cpg-network:
    driver: bridge 