version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/cpgmatching
      - AI_SERVICE_URL=http://ai-service:5001/api
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongodb
    networks:
      - app-network
      
  ai-service:
    build:
      context: ../AI
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/cpgmatching
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongodb
    networks:
      - app-network
      
  frontend:
    build:
      context: ../FE
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
      - VITE_AI_API_BASE_URL=http://localhost:5000/api/ai-proxy
    depends_on:
      - backend
      - ai-service
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 